### ISSUE TITLE
Implement bitwise operators for multi-wire busses

### ISSUE THREAD

**Issue by Ben1152000** [Ben1152000/sootty#4]
Right now you can use &, |, and ! as logical operations, but there's no clean way to do bitwise operations. These operators can be repurposed to act as bitwise (plus ~) and &&, ||, and ! can represent logical operations.

**Comment by KarthikL1729** [comment]
This issue can probably be closed now?

**Comment by KarthikL1729** [comment]
Closed by PRs #38 and #43.
